"""Pydantic Schemas Package."""
from app.schemas.job import JobRequirements, JobCreate, JobUpdate, JobResponse
from app.schemas.candidate import (
    CandidateEducation,
    CandidateExperienceItem,
    CandidateProject,
    CandidateProfile,
    CandidateCreate,
    CandidateResponse,
)
from app.schemas.evaluation import (
    EvidenceSnippet,
    SkillMatchResult,
    SkillGapItem,
    SkillGapResult,
    ScoreBreakdown,
    InterviewQuestionItem,
    InterviewQuestionsResult,
    InterviewQuestionResponse,
    CandidateReport,
    ValidationResult,
    EvaluateCandidateRequest,
    BatchEvaluateRequest,
    EvaluationResponse,
    BatchEvaluateItem,
    BatchEvaluateResponse,
)
from app.schemas.agent import (
    AgentStepSchema,
    AgentRunResponse,
    ToolInfo,
    AgentStatusResponse,
)
from app.schemas.decision import (
    RecruiterDecisionCreate,
    RecruiterDecisionResponse,
    RecruiterNoteCreate,
    RecruiterNoteResponse,
)
from app.schemas.knowledge import (
    KnowledgeDocCreate,
    KnowledgeDocResponse,
    ChunkResponse,
    KnowledgeQueryRequest,
    KnowledgeQueryResult,
)

__all__ = [
    "JobRequirements",
    "JobCreate",
    "JobUpdate",
    "JobResponse",
    "CandidateEducation",
    "CandidateExperienceItem",
    "CandidateProject",
    "CandidateProfile",
    "CandidateCreate",
    "CandidateResponse",
    "EvidenceSnippet",
    "SkillMatchResult",
    "SkillGapItem",
    "SkillGapResult",
    "ScoreBreakdown",
    "InterviewQuestionItem",
    "InterviewQuestionsResult",
    "CandidateReport",
    "ValidationResult",
    "EvaluateCandidateRequest",
    "BatchEvaluateRequest",
    "EvaluationResponse",
    "BatchEvaluateItem",
    "BatchEvaluateResponse",
    "AgentStepSchema",
    "AgentRunResponse",
    "ToolInfo",
    "AgentStatusResponse",
    "RecruiterDecisionCreate",
    "RecruiterDecisionResponse",
    "RecruiterNoteCreate",
    "RecruiterNoteResponse",
    "KnowledgeDocCreate",
    "KnowledgeDocResponse",
    "ChunkResponse",
    "KnowledgeQueryRequest",
    "KnowledgeQueryResult",
]
