"""Prompts package."""
from app.prompts.job_analysis import JOB_ANALYSIS_SYSTEM_PROMPT, JOB_ANALYSIS_USER_TEMPLATE
from app.prompts.resume_analysis import RESUME_ANALYSIS_SYSTEM_PROMPT, RESUME_ANALYSIS_USER_TEMPLATE
from app.prompts.matching import MATCHING_SYSTEM_PROMPT, MATCHING_USER_TEMPLATE
from app.prompts.skill_gap import SKILL_GAP_SYSTEM_PROMPT, SKILL_GAP_USER_TEMPLATE
from app.prompts.interview import INTERVIEW_SYSTEM_PROMPT, INTERVIEW_USER_TEMPLATE
from app.prompts.reporting import REPORT_SYSTEM_PROMPT, REPORT_USER_TEMPLATE
from app.prompts.validation import VALIDATION_SYSTEM_PROMPT, VALIDATION_USER_TEMPLATE
from app.prompts.agent import AGENT_PLANNER_SYSTEM_PROMPT

__all__ = [
    "JOB_ANALYSIS_SYSTEM_PROMPT",
    "JOB_ANALYSIS_USER_TEMPLATE",
    "RESUME_ANALYSIS_SYSTEM_PROMPT",
    "RESUME_ANALYSIS_USER_TEMPLATE",
    "MATCHING_SYSTEM_PROMPT",
    "MATCHING_USER_TEMPLATE",
    "SKILL_GAP_SYSTEM_PROMPT",
    "SKILL_GAP_USER_TEMPLATE",
    "INTERVIEW_SYSTEM_PROMPT",
    "INTERVIEW_USER_TEMPLATE",
    "REPORT_SYSTEM_PROMPT",
    "REPORT_USER_TEMPLATE",
    "VALIDATION_SYSTEM_PROMPT",
    "VALIDATION_USER_TEMPLATE",
    "AGENT_PLANNER_SYSTEM_PROMPT",
]
